networks:
  net:
    name: net
    driver: bridge

services:
  mitm_proxy:
    build:
      context: .
      dockerfile: Dockerfile.mitm_proxy
    container_name: mitm_proxy
    ports:
      - "9400:9400"
    networks:
      - net
    environment:
      - PY_SERVER_HOST=server
      - PY_SERVER_PORT=5000
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    env_file:
      - ./server/.env
    environment:
      - FOCUS=study networks, nothing else
      - LLM_MODEL=gpt-4o-mini
    ports:
      - "5001:5001"
    networks:
      - net

